### ISSUE TITLE
Register the user in the DB

### ISSUE THREAD

**Issue by martchellop** [martchellop/Entretenibit#126] opened 2018-06-11 19:53 UTC
Get the information from the sing up done in #125 and insert that in our data base.

**Comment by BrunoGomesCoelho** [comment] 2018-06-22 18:02
@matheushjs what is the check to insert or not a user in the database via the site?

Any e-mail I try gives me the 

> Sentimos muito! Não foi possível cadastrá-lo no sistema.

alert, and doesn't insert it into the database.

Bit if I connect to the database through psql -U entretenibit -h [DB_SERVER_IP] and manually insert the same e-mail into the database, it works.

**Comment by matheushjs** [comment] 2018-06-22 21:17
The database makes sure e-mails have the format [something]@[something]; that is, 2 non-empty substrings separated by a '@'.

I don't seem to be able to reproduce your problem. I've tried to register an e-mail and got (I've cut unimportant lines):

```
server_1    | GET /insertUser?email=teste9@hotmail.com&name=Matheus&searchStr=Alguma+Coisa&academic=true&music=true&theater=true&others=true&pmin=0&pmax=0 200 414.565 ms - 7
[...]
server_1    | GET /insertUser?email=teste9@hotmail.com&name=Matheus&searchStr=Alguma+Coisa&academic=true&music=true&theater=true&others=true&pmin=0&pmax=0 500 359.154 ms - 753
```

Where the first request receives HTTP response code 200, and the next one 500, which represent respectively a success and a failure.

I'm surprised with the error line you pasted, though:
```
server_1 | 17:52:23 error: connect ECONNREFUSED 127.0.0.1:5432
```
Is it trying to connect to IP 127.0.0.1 in port 5432? That's what the error seems to be saying.
It isn't supposed to do that, since my IP is 179.X.X.X. Have you checked the `.env` file in the server directory?

**Comment by BrunoGomesCoelho** [comment] 2018-06-23 17:50
Got it working! The problem was a mix of the .env file and docker-compose not rebuilding the images.

>  Have you checked the .env file in the server directory?

Thanks! The .env file was indeed missing, I only had it in my robot directory.

The other problem was that `docker-compose --force-rebuild up` didn't update the images, so even though I had pasted the .env file, it still wouldn't work. In the end, `docker-compose build` was necessary to update the images; not sure why the force command didn't work, maybe I read it wrong but everything is working now! Closing this.

**Closed by BrunoGomesCoelho** 2018-06-23 17:50 UTC
Labels: enhancement, priority: high
